### ISSUE TITLE
ERROR	Database error: near "Destination": syntax error

### ISSUE THREAD

**Issue by tctx79** [lazylibrarian/LazyLibrarian#13]
Anyone else receiving this error?  If I need to provide any more detailed information please let me know.

**Comment by tctx79** [comment]
This is showing up in my terminal window:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/***/Downloads/LazyLibrarian/lazylibrarian/librarysync.py", line 433, in LibraryScan
    author).fetchone()
  File "/Users/***/Downloads/LazyLibrarian/lazylibrarian/database.py", line 41, in action
    sqlResult = self.connection.execute(query)
OperationalError: near "Destination": syntax error

**Comment by tctx79** [comment]
FYI I am on a ~2010 iMac running OSX El Capitan if that helps.
