### ISSUE TITLE
Error when trying to refresh/add author

### ISSUE THREAD

**Issue by tgrossner** [lazylibrarian/LazyLibrarian#6]
2015-04-08 11:07:41	ERROR	Error fetching authorid: undefined entity: line 51, column 36

**Comment by danb35** [comment]
I seem to be running into the same issue:
26-Apr-2015 06:34:22 - INFO :: DBIMPORT : Now adding new author: Jane Austen to database
26-Apr-2015 06:34:22 - DEBUG :: DBIMPORT : Searching for author with name: {'id': 'Jane Austen'}
26-Apr-2015 06:34:22 - ERROR :: DBIMPORT : Error fetching authorid: undefined entity: line 51, column 36
Exception in thread DBIMPORT:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/LazyLibrarian-master/lazylibrarian/importer.py", line 31, in addAuthorToDB
    author = GR.find_author_id()
  File "/LazyLibrarian-master/lazylibrarian/gr.py", line 158, in find_author_id
    rootxml = sourcexml.getroot()
UnboundLocalError: local variable 'sourcexml' referenced before assignment

Running python 2.7.9 on FreeBSD 9.2 (in a FreeNAS jail).

**Comment by blindpet** [comment]
I am getting this error too on Windows running python 2.7.9.

**Comment by Bacchusm** [comment]
Any help on this DBIMPORT exception?
